rickeyski/slack-api

- src/Web/Slack.hs
I've had a small problem: when my computer goes to sleep mode, the websocket connection get severed (after a timeout), but this is not detected and the bot simply hangs.
I solved that by adding a ping every 10 seconds (the websockets package provide a nice function for this). Now, when the connection is severed, an IOException is raised and I can restart the bot.
> Added a ping thread, so that the WS client crashes when it should

- slack-api.cabal
We only use readz from errors, and it wasn't affected by the interface
change, so it is safe use errors 2.0
> Raised the upper bound for errors from <2.0 to <3.0

- src/Web/Slack/Types/Event.hs
This commit adds a constructor and JSON parsing for the `status_change` event.  This message doesn't appear to be documented in [the Slack RTM API docs](https://api.slack.com/rtm).  Googling doesn't turn up many hits, but there does seem to be a `status_change` message in Slack's official node/coffeescript bot [here](https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L360).  I used that code and the error message from #20 to guess at the structure of this event, and it seems to work for me, but I guess it would be good to ask what's going on upstream as well.
> Add 'status_change' event

- src/Web/Slack/Types/Event.hs
This commit adds constructors and JSON parsing for [`reaction_added`](https://api.slack.com/events/reaction_added) and [`reaction_removed`](https://api.slack.com/events/reaction_removed) events.
This addresses [Issue 21](https://github.com/mpickering/slack-api/issues/21).
> Add 'reaction_added' and 'reaction_removed' events

- src/Web/Slack/Types/Event.hs
I got the behavior wrong for the reaction events -- apparently the `name` field is optional (though the docs never imply this . . .)
> Make the 'name' field of reaction events optional (this is undocumented)

- src/Web/Slack/Types/Channel.hs
> Make the 'is_archived' field of channel objects optional

- src/Web/Slack/Types/Event.hs
Proposed fix to #38. From the documentation (https://api.slack.com/events/team_migration_started), it appears the client will get disconnected after this event is sent. It appears for now that any reconnection logic should be handled by the user, rather than included in this module, so I have not spent much time looking into that area.
> Add TeamMigrationStarted Event Type

- src/Web/Slack/Types/Event.hs
When leaving client connected, get periodic JSON with type of "reconnect_url"
and a websocket URL in the "url" field. Documentation seems to indicate that
when a client gets disconnected, the correct resolution is to call rtm.start
method again. Unsure what the correct course is, but adding support for
the type.
Below is example of JSON response:
{
"type": "reconnect_url",
"url": "wss://mp.slack-msgs.com/websocket/yAj-3m8m-jVvwipOeGxPEJxsXbOma3h0kTsAnVK4eoYIOmek8BSZK702O8mqYoTBYgQ_9bLH6QN-TiQqS_-_bJUnMi6g8uvZ3tA4Jt3zlX-3VrUfM7-DSziJuYjjdLlHu0twpZjty7I8SHARqCfIgk4l_DzTrGeyWLicKHR-W60="
}
> Add ReconnectUrl type

- src/Web/Slack/Types/Id.hs
This allows library users to construct Id types from text. This is
really useful when the id was stored in a database as a string and needs
to be constructed back into it's Id type before using it with this
library. 
Solves #54
> Export Id constructors

- src/Web/Slack/Types/Time.hs
Slack's API sometimes returns strings and sometimes returns integers for
times. This was causing the `channel_rename` feature to fail, since it
was returning the channels `created` attribute as a string, and we were
only parsing integer values. This commit fixes that by adding a second
function head to parse string values.
Fixes: https://github.com/mpickering/slack-api/issues/34
> Be more flexible parsing inconsistent Time values

- slack-api.cabal
- src/Web/Slack.hs
Replace HsOpenSSL with tls.
This replaces the dependency on OpenSSL with a pure Haskell based
version. Also adds tfausak/wuss, which abstracts away the secure
websocket initialization.
Fixes #62
> Drop OpenSSL

- src/Web/Slack/Types/Preferences.hs
It looks like these fields were removed from the rtm startup preferences. I have no idea what they are used for. I just noticed that our slack bot wouldn't start any more because these fields were missing.
I did a curl against the rtm start endpoint like so:
```sh
curl https://slack.com/api/rtm.start -F token=my_token
```
...and indeed these fields were not present.
> Remove nonexistent fields from Preferences

- src/Web/Slack/Types/Team.hs
This PR changes the `_teamIconDefault` type from `Bool` to `String` to get things working in #78.
I see this as a temporary fix because like @srhb reported on #78, the [slack docs](https://api.slack.com/methods/rtm.start) are misleading: https://github.com/slackhq/slack-api-docs/issues/79
> Fixes #78: type mismatch for _teamIconDefault - changed Bool to String

- CHANGELOG
- src/Web/Slack/Types/Team.hs
This reverts the temporary changes from #79 (issue #78).  Slack HQ has fixed the type problem, so we can revert the default team icon type back to `Bool`.
Please see this slack issue for more info:  https://github.com/slackhq/slack-api-docs/issues/79
> Type mismatch for team icon has been fixed by Slack HQ - revert #78

- CHANGELOG
- slack-api.cabal
- src/Web/Slack/Types/Time.hs
This change is necessary for API functions that require timestamps to be sent back to Slack. We don't want to lose precision by storing unix timestamps as floating-point values.
> Change type of Time from NominalDiffTime to Int

- src/Web/Slack/Types/Preferences.hs
Slack doesn't seem to be returning this field for us anymore, which
leads to crashes at startup unless we remove the field.
> Remove email_misc field from Preferences

- src/Web/Slack/Types/Preferences.hs
Slack doesn't seem to be returning this field for us anymore, which
leads to crashes at startup unless we remove the field.
> Remove full_text_extracts field from Preferences

- src/Web/Slack/Types/Event/Subtype.hs
This allows for easier inspection for missing or changed subtypes in the Slack API documentation which is also in lexicographical order.
> Put Message Subtypes In Lexicographical Order

- .gitignore
While working on #103 I noticed these locally generated files or directories were not ignored in `.gitignore`. Kept this commit separate from the other patch to keep their acceptance independent. Thanks.
> Add .ghc.environment.*, dist-newstyle, and dist to .gitignore

- src/Web/Slack/Types/Event.hs
- src/Web/Slack/Types/File.hs
The "file\_change" event did not conform to the Slack API. It was attempting to read an entire "file" object, as though this was a "file\_created" event. Making matters a bit more complicated the Slack API itself does not correctly document all of the fields on the event.
Due to the somewhat large number of fields, and in an attempt to keep with general idioms for the `Event` GADT, the `FileChange` event now wraps a `FileChangeInfo` value. The primary advantage here is that we get record functions for accessing the members. In the future we may want to consider some more significant changes.
> Correct FileChange Event
